name: Manual Deploy SafetyLens

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name for deployment'
        required: true
        type: string
      branch:
        description: 'Branch to deploy'
        required: true
        type: string
        default: 'main'
      port:
        description: 'Port number for the server'
        required: true
        type: string
        default: '9000'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ${{ inputs.environment_name }}
          
      - name: Start server using GitHub Actions
        env:
          PORT: ${{ inputs.port }}
        run: |
          npm run build
          nohup npm run start:server > server.log 2>&1 &
          echo "Server started on port $PORT"
          
      - name: Health check
        run: |
          sleep 10
          curl -f http://localhost:${{ inputs.port }}/health || exit 1 